/*
 * SPDX-FileCopyrightText: 2025 Budapest University of Technology and Economics
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0/samples
 */

plugins {
    java
    jacoco
    application
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

tasks {
    test {
        // Specify that after this task jacoco must also run (at some point)
        finalizedBy(jacocoTestReport)
    }
    
    jacocoTestReport {
        // Specify that this task uses the test task's outputs
        inputs.files(test.get().outputs)
    }
}

application {
    mainClass = "hu.bme.mit.ase.passwordchecker.app.Main"
}

dependencies {
    implementation(project(":service"))
    implementation(libs.slf4j.api)
    runtimeOnly(libs.slf4j.simple)
    implementation(libs.jcommander)

    testImplementation(libs.junit.jupiter.core)
    testRuntimeOnly(libs.junit.jupiter.engine)
    testRuntimeOnly(libs.junit.platform.launcher)
    
}

tasks.test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
}