# SPDX-FileCopyrightText: 2025 Budapest University of Technology and Economics
#
# SPDX-License-Identifier: Apache-2.0

name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: adopt
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle build
        run: ./gradlew build
      - name: Upload Artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
         path: |
           **/build/distributions/*

  e2e-integration:
    name: integration-test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: adopt
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Download Distribution
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: artifact
      - name: Extract Distribution
        uses: ihiroky/extract-action@v1
        with:
          file_path: artifact/app/build/distributions/app.tar
          extract_dir: dist
      - name: Test app
        run: |
          ./app/build/install/app/bin/app --password 12345678 --loglevel WARN | grep "Strength: WEAK"
          ./app/build/install/app/bin/app --password 1agr3dfh34 --loglevel WARN | grep "Strength: MEDIUM"
          ./app/build/install/app/bin/app --password 1fg*qwTerSH2 --loglevel WARN | grep "Strength: STRONG"